<?php

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function jira_transfer_logged_time_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'jira_transfer_logged_time/vue';
}

function jira_transfer_logged_time_theme($existing, $type, $theme, $path) {
  return [
    'jira' => [
      'variables' => [
        'initial_data' => NULL,
      ],
    ],
  ];
}
